{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c1e8f30b_3ef750b8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2024-01-19T15:15:43Z",
      "side": 1,
      "message": "You\u0027ve given no explanation why.  We need to stop adding InternalFailure because there is absolutely nothing that a client can do with it.  Why does setting the hostname property result in an internal failure?",
      "revId": "17fd7558c7dddd066271360d2fbbb5601ec32bd9",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}